### ISSUE TITLE
please use a GPL compatible license

### ISSUE THREAD

**Issue by fommil** [LuxLang/lux#5]
The EPL is not compatible with the GPL :cry: can you please relicense under something that is compatible? Some ideas here https://en.wikipedia.org/wiki/License_compatibility#GPL_compatibility

I'd personally prefer if you chose a copyleft license such as LGPL or MPL as that would ensure that the language remains free.

**Comment by wizardbeard** [comment]
Not everyone loves the GPL, nor should they necessarily be forced to use a GPL-flavored license.

**Comment by LuxLang** [comment]
@fommil 

I'm not a licenses buff, so I really don't know of any negative impact that the EPL might have on Lux users.

Could you please tell me what problems would arise from using the EPL and how does the EPL not make Lux free?

I'm willing to consider a *GPL license if it doesn't force users to have to make their own software free (or impose any other uncomfortable restrictions).

**Comment by fommil** [comment]
@LuxLang it means that users can't use Lux to write GPL applications :cry:

**Comment by fommil** [comment]
@LuxLang if you chose LGPL or MPL it would **not** force users to use GPL for their app, but it would allow them to do so. It would also have the added benefit that any changes that anybody makes to Lux would also have to be made available, so that you could have the option to incorporate it back into the language.

In contrast, if you used an open source / free software license such as Apache license, then people could create their own version of Lang without ever sharing the source code with you.

This is the difference between "free software" and "copyleft".

**Comment by LuxLang** [comment]
I'll take a look at both LGPL & MPL and see if they're a good fit for Lux.

**Comment by wizardbeard** [comment]
I recommend the MIT license as it doesn't force commercial developers to release proprietary code back to the community at large.

-----Original Message-----

**Comment by fommil** [comment]
@wizardbeard if the language is LGPL or MPL, it doesn't mean that users of Lux would need to change their licenses i.e. you could still build proprietary systems on top of an LGPL Lux. Indeed, if there is no runtime component to Lux, you could even make it GPL and users still wouldn't need to release (as is the case for both Java and GCC, actually).

My recommendation is for the Lux compiler to be GPL (same as `javac`) and the standard library to be (in decreasing order of preference) LGPL, MPL or Apache. The smaller the standard library, the better.

However, I encourage you to make an informed decision, based on your own priorities, have a look at http://choosealicense.com/

**Comment by wizardbeard** [comment]
MIT license is superior in every way.  Why do GPL enthusiasts always come across as entitled to fruits of another organization's commerical labor?  javac is ubiquitous largely due to a massive advertising budget in the 1990's.

**Comment by fommil** [comment]
I believe this is a choice to be made by the authors of Lux. Let's give them time to make an informed decision for:

1. the compiler (which won't imply anything to the license of applications written in Lux)
2. the standard library (which might have consequences on bundling of downstream applications)

which can be:

* Copyleft Free Software licenses (such as LGPL, MPL) will ensure that extensions to Lux are shared back to the Lux community.
* Free Software licenses (such as Apache, MIT, BSD) will mean that only the official Lux distribution are guaranteed to have the source code available, and community changes may be proprietary.

I encourage GPL for the compiler (precedent set by `javac` and `gcc`), and MPL for the standard library because that means that you are as copyleft as you can possibly get without demanding anything of Lux applications https://www.mozilla.org/MPL/2.0/FAQ.html#virality I believe this is probably what the Clojure EPL was trying to achieve, but it is just a broken license.

On the other hand, there are examples of languages and compilers actually encouraging that proprietary extensions are created, e.g. LLVM. In that case, you might want to look at the LLVM license for everything. The choice is yours.

**Comment by bodil** [comment]
Regardless of the merits of the GPL, choosing a licence which doesn't actively prohibit users from applying the GPL to their own software is _not_ the same as forcing the GPL's restrictions on everybody. @wizardbeard, suggesting such a thing is somewhat disingenuous.

I did a lot of research into the issue of the Eclipse licence and its incompatibilities when I was doing Clojure, and my licence of choice given the restrictions the EPL imposes was Apache version 2. I'd recommend against the Mozilla licence, as you'll end up spending a lot of time adding it to every source file - that's the level that licence is designed for, whereas most other licences can be applied at the project level. The LGPL is also an option (Eclipse is only incompatible with GPL v2 and v3 specifically, not LGPL), but Apache is probably a safer choice as well as a less controversial one.

Either way, as long as it's not the EPL, which would likely prohibit me from licensing Lux programs I write under the GPL, I won't mind. :blush:

**Comment by fommil** [comment]
Heh, I just realised that if EPL of Clojure means you can't write GPL software with it, then you actually can't release your compiler as GPL... it could only be LGPL if it were to be copyleft.

OK, in that case I change my recommendation to:

* LGPL for the compiler
* MPL or Apache for the standard library

**Comment by fommil** [comment]
@bodil where did you see that file header boilerplate is needed? https://www.mozilla.org/MPL/2.0/FAQ.html#full-copy-only seems to suggest that MPL can be applied project-wide. (sorry, if we're hijacking the thread we can take it to twitter or gitter)

**Comment by bodil** [comment]
@fommil It's entirely possible I missed that on my reading of the MPL. :blush: That's good news, then - the MPL is a good licence too, apart from that requirement I was too lazy to oblige which apparently isn't a strict requirement after all.

I'd recommend using the same licence for the compiler and the standard library, though, or things could get more complicated than they need to be.

**Comment by fommil** [comment]
@bodil also, https://github.com/fommil/dotfiles/blob/master/.emacs.d/init.el#L218 would have solved that even if it was a requirement :wink: c.f. https://github.com/fommil/dotfiles/blob/master/.emacs.d/snippets/scala-mode/newfile https://github.com/fommil/dotfiles/blob/master/.emacs.d/snippets/emacs-lisp-mode/newfile

**Comment by wizardbeard** [comment]
Forcing developers to release their patches under the GPL is antithetical to the ideals of freedom that the FSF pays so much lip service to.

-----Original Message-----

**Comment by melrief** [comment]
The developer is free to pick the license and "force" patches under that license. This makes a lot of sense because in this way you avoid all the problems related to patches with a different license than the one of the project.

**Comment by kryptt** [comment]
@wizardbeard No one should ever argue freedom has no bounds. An individual's freedom stops once it encroaches over another's. Different people / projects / teams have different priorities. 

Licences and codes of conduct set the boundaries each team / project is comfortable with. Some projects expect you to trust blindly and use as directed, others require you to share your patches back, another group might not care, forfeit their property rights and offer the code up to *'public domain'*.

**Comment by LuxLang** [comment]
Alright, so I've read about Apache 2.0, LGPL 3.0 & MPL 2.0

Apache seems lightweight, but I don't like the idea of someone taking my code and making all kinds of changes without contributing anything back. It's not a huge problem for me, but I'd rather avoid it.

LGPL seems like it's out of the question. At first it sounded reasonable, but I looked up criticisms of it on Google and found something that I didn't notice when I read the license.
Apparently, if you use a library under LGPL that's statically linked, you must put in place some kind of separation to ensure independence and (it seems) "swappability" of the LGPL code.
There are links at the bottom where I read those issues.

Since, in the future, I plan to make the compiler more like a library, so people can embed it for the sake of scripting or things of that nature, I don't want the license to put people in tough spots.

I want to protect the compiler from people shamelessly taking it without giving anything back to the project, but measures like that sound a bit exaggerated to me. For that reason, LGPL will not be considered.
**Note**: _If anyone knows better about how the LGPL works and can debunk the issue I mentioned, feel free to speak out_

MPL seems reasonable:
* Code gets protected and can't be taken away.
* Only affects licensed files and doesn't spread to other code, so it lacks the *GPL's virality.

I'm thinking of making the shift to MPL for both compiler & standard library.
Does anyone here have any objection?

**Ideals of the Project**
* The compiler & the standard library must be free & available to everyone, forever.
* People shouldn't be able to take any of the project's code and just change it and create derived work without contributing back what they made (that means they're profiting from other people's work but not giving anything back).
* Nobody should be forced to open-source their independent work just because they used the compiler or standard libraries.
* It should be possible to use the compiler as a library without the license infecting foreign code. The only thing that should be forbidden is creating new software by modifying the compiler and then keeping that to yourself.

With those goals in mind, hopefully everyone can now understand where I stand when it comes the licensing of Lux and what licenses can be considered for the language.
Since many of you have expressed interest in a GPL-compatible language, I have no problem making a transition. I just want to make sure those goals are not transgressed.

___

**Links**:
http://programmers.stackexchange.com/questions/47323/can-i-use-an-lgpl-licenced-library-in-my-commercial-app
http://programmers.stackexchange.com/questions/86142/what-exactly-do-i-need-to-do-if-i-use-a-lgpl-licenced-library

**Comment by fommil** [comment]
:smile:

**Comment by GlenKPeterson** [comment]
If you use the Mozilla Public License, and I get permission at work to contribute to this project and I actually make a code contribution, I have then modified the code.  Does that mean that when I use the modified version at work, that we have to distribute our proprietary source when we distribute our executable, because now we've modified your code?

I can use Apache, MIT, BSD, and Eclipse-licensed code at work.  LGPL or GPL v2 is acceptable only unmodified and with the "Classpath exception."  I like Apache because:
 - It spells out the details of derivative works (unlike MIT/BSD)
 - It removes people's rights to use it if they sue you for patent infringement (like EPL)
 - It is well established and tested in international courts (compared to most other F/OSS licenses)
 - those who want can convert derivative works to GPL v3.

**Comment by SethTisue** [comment]
re: LGPL, you're right that it treats dynamic and static linking differently. but does anybody statically link libraries anymore? it seems like an edge case to me rather than a serious downside.

(regardless, I think MPL is a fine choice)

**Comment by fommil** [comment]
@GlenKPeterson you'd have to distribute your source modifications of Lux, but not of your app. But in your scenario, you've already obliged that requirement by making a "code contribution" (which I assume you meant was back to LuxLang) so you wouldn't have any further action to take.

**Comment by fommil** [comment]
@SethTisue there was a clarifying point made by the FSF on this in the JVM http://www.gnu.org/licenses/lgpl-java.en.html

It's still open to interpretation, but I would consider a single jar bundle to be equivalent to static linking, which is relevant for some people.

**Comment by wizardbeard** [comment]
I think the MPL is a fine choice over GPL and LGPL for the reasons you enumerated.

-----Original Message-----

**Comment by LuxLang** [comment]
@GlenKPeterson:
As I understand it, you only need to release your changes to the compiler. If your apps uses the modified compiler, it doesn't matter. The MPL doesn't cover your app, only the contributions to the compiler (and you were going to release it anyway).

@SethTisue I agree with @fommil regarding the static linking issue.
Imagine creating an uberjar of your program that contains the Lux standard library and imagine the stdlib is LGPL. You might get into trouble...

**Comment by fommil** [comment]
@LuxLang @GlenKPeterson and to the stdlib

**Comment by bodil** [comment]
I've no objections to the MPL, which is a fine, strong copyleft licence, but as has been previously mentioned, Apache 2 contains provisions for patent trolling, like the EPL and *GPL, whereas the MPL does not. (And, ironically, people are telling me the exact wording of the patent provisions is what actually makes the EPL and GPL incompatible.) Whether that's an issue or not is up to you - if it is, then based on your requirements it sounds like you want the LGPL, or even the GPL, with an exception clause. I'm not sure if the Classpath exception is a good fit for this, but I think it could be. IANAL etc...

**Comment by GlenKPeterson** [comment]
OK, so because I've contributed the modification back to the original source, when I refresh the project from the original source it counts as unmodified.  Seems very reasonable.  Thanks for the clarification!

**Comment by LuxLang** [comment]
@bodil Check this out: http://en.swpat.org/wiki/Patent_clauses_in_software_licences#Mozilla_Public_License

**Comment by bodil** [comment]
Oh, in that case, I'd say the choice is obvious. :blush:

**Comment by LuxLang** [comment]
Seems like there's agreement.
I'll wait until the end of the day in case anybody else pops up with a complaint.

If by the end of the day the consensus holds, MPL will be the chosen one.

**Comment by yurrriq** [comment]
Generally I prefer BSD, MIT or something even more open (WTF, public domain), but in this case MPL seems like a good compromise and probably the best fit.

**Comment by LuxLang** [comment]
The day is over and consensus has been maintained.
MPL is the chosen one.

As soon as I'm done with a set of changes to the compiler I'm working on, I'll make a new commit changing the license.

**Comment by yurrriq** [comment]
:tada:

**Comment by bodil** [comment]
Much appreciated. :blush:

**Comment by fommil** [comment]
:+1:

**Comment by kirked** [comment]
@LuxLang The README still claims EPL!

**Comment by LuxLang** [comment]
@kirked That's because you're looking at the v0.2 README.
The README will state MPL for v0.3 onwards.
